import { describe, expect, it } from "bun:test";

import { generateBashCompletions } from "../../src/completions/bash";
import type { CommandData } from "../../src/completions/types";

describe("bash completions", () => {
  it("generates basic completion script with header", () => {
    const data: CommandData = {
      name: "my-cli",
      description: "Test CLI",
      options: [],
      subcommands: [],
    };

    const script = generateBashCompletions(data);

    expect(script).toContain("# Bash completions for my-cli");
    expect(script).toContain("# Generated by @truyman/cli");
    expect(script).toContain("_my_cli_completions()");
    expect(script).toContain("complete -F _my_cli_completions my-cli");
  });

  it("includes --help option by default", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [],
      subcommands: [],
    };

    const script = generateBashCompletions(data);

    expect(script).toContain("--help");
    expect(script).toContain("-h");
  });

  it("includes custom options", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [
        { long: "verbose", short: "v", type: "boolean", description: "Verbose output" },
        { long: "output", short: "o", type: "string", description: "Output file" },
      ],
      subcommands: [],
    };

    const script = generateBashCompletions(data);

    expect(script).toContain("--verbose");
    expect(script).toContain("-v");
    expect(script).toContain("--output");
    expect(script).toContain("-o");
  });

  it("includes subcommands in completion", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [],
      subcommands: [
        { name: "init", description: "Initialize", options: [], subcommands: [] },
        { name: "build", description: "Build project", options: [], subcommands: [] },
      ],
    };

    const script = generateBashCompletions(data);

    expect(script).toContain("init build");
  });

  it("handles nested subcommands", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [],
      subcommands: [
        {
          name: "config",
          description: "Config commands",
          options: [],
          subcommands: [
            { name: "get", description: "Get config", options: [], subcommands: [] },
            { name: "set", description: "Set config", options: [], subcommands: [] },
          ],
        },
      ],
    };

    const script = generateBashCompletions(data);

    expect(script).toContain("config)");
    expect(script).toContain("get set");
  });

  it("excludes hidden commands from completions", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [],
      subcommands: [
        { name: "visible", description: "Visible command", options: [], subcommands: [] },
        {
          name: "hidden",
          description: "Hidden command",
          hidden: true,
          options: [],
          subcommands: [],
        },
      ],
    };

    const script = generateBashCompletions(data);

    expect(script).toContain("visible");
    expect(script).not.toMatch(/commands="[^"]*hidden/);
  });

  it("sanitizes command names with special characters", () => {
    const data: CommandData = {
      name: "my-special-cli",
      options: [],
      subcommands: [],
    };

    const script = generateBashCompletions(data);

    expect(script).toContain("_my_special_cli_completions()");
  });
});
