import { describe, expect, it } from "bun:test";

import { generateFishCompletions } from "../../src/completions/fish";
import type { CommandData } from "../../src/completions/types";

describe("fish completions", () => {
  it("generates basic completion script with header", () => {
    const data: CommandData = {
      name: "my-cli",
      description: "Test CLI",
      options: [],
      subcommands: [],
    };

    const script = generateFishCompletions(data);

    expect(script).toContain("# Fish completions for my-cli");
    expect(script).toContain("# Generated by @truyman/cli");
    expect(script).toContain("# Save to ~/.config/fish/completions/my-cli.fish");
    expect(script).toContain("complete -c my-cli -f");
  });

  it("includes --help option by default", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [],
      subcommands: [],
    };

    const script = generateFishCompletions(data);

    expect(script).toContain("-s h -l help -d 'Show help'");
  });

  it("includes custom options with descriptions", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [
        { long: "verbose", short: "v", type: "boolean", description: "Verbose output" },
        { long: "output", short: "o", type: "string", description: "Output file" },
      ],
      subcommands: [],
    };

    const script = generateFishCompletions(data);

    expect(script).toContain("-s v -l verbose -d 'Verbose output'");
    expect(script).toContain("-s o -l output -r -d 'Output file'");
  });

  it("uses -r flag for non-boolean options", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [
        { long: "count", type: "number", description: "Count" },
        { long: "file", type: "string", description: "File path" },
        { long: "quiet", type: "boolean", description: "Quiet mode" },
      ],
      subcommands: [],
    };

    const script = generateFishCompletions(data);

    expect(script).toContain("-l count -r -d 'Count'");
    expect(script).toContain("-l file -r -d 'File path'");
    expect(script).toContain("-l quiet -d 'Quiet mode'");
    expect(script).not.toContain("-l quiet -r");
  });

  it("includes subcommands in completion", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [],
      subcommands: [
        { name: "init", description: "Initialize project", options: [], subcommands: [] },
        { name: "build", description: "Build project", options: [], subcommands: [] },
      ],
    };

    const script = generateFishCompletions(data);

    expect(script).toContain("-a init -d 'Initialize project'");
    expect(script).toContain("-a build -d 'Build project'");
  });

  it("uses __fish_use_subcommand for top-level with subcommands", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [],
      subcommands: [{ name: "init", description: "Initialize", options: [], subcommands: [] }],
    };

    const script = generateFishCompletions(data);

    expect(script).toContain("-n __fish_use_subcommand");
  });

  it("uses __fish_seen_subcommand_from for nested completions", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [],
      subcommands: [
        {
          name: "config",
          description: "Config commands",
          options: [{ long: "global", type: "boolean", description: "Global" }],
          subcommands: [],
        },
      ],
    };

    const script = generateFishCompletions(data);

    expect(script).toContain("__fish_seen_subcommand_from config");
  });

  it("handles nested subcommands", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [],
      subcommands: [
        {
          name: "config",
          description: "Config commands",
          options: [],
          subcommands: [
            { name: "get", description: "Get config", options: [], subcommands: [] },
            { name: "set", description: "Set config", options: [], subcommands: [] },
          ],
        },
      ],
    };

    const script = generateFishCompletions(data);

    expect(script).toContain("-a get -d 'Get config'");
    expect(script).toContain("-a set -d 'Set config'");
  });

  it("excludes hidden commands from completions", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [],
      subcommands: [
        { name: "visible", description: "Visible command", options: [], subcommands: [] },
        {
          name: "hidden",
          description: "Hidden command",
          hidden: true,
          options: [],
          subcommands: [],
        },
      ],
    };

    const script = generateFishCompletions(data);

    expect(script).toContain("-a visible -d 'Visible command'");
    expect(script).not.toContain("-a hidden");
  });

  it("escapes single quotes in descriptions", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [{ long: "test", type: "boolean", description: "It's a test" }],
      subcommands: [],
    };

    const script = generateFishCompletions(data);

    expect(script).toContain("It\\'s a test");
  });
});
