import { describe, expect, it } from "bun:test";

import { generateZshCompletions } from "../../src/completions/zsh";
import type { CommandData } from "../../src/completions/types";

describe("zsh completions", () => {
  it("generates basic completion script with header", () => {
    const data: CommandData = {
      name: "my-cli",
      description: "Test CLI",
      options: [],
      subcommands: [],
    };

    const script = generateZshCompletions(data);

    expect(script).toContain("#compdef my-cli");
    expect(script).toContain("# Zsh completions for my-cli");
    expect(script).toContain("# Generated by @truyman/cli");
    expect(script).toContain("_my_cli()");
  });

  it("includes --help option by default", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [],
      subcommands: [],
    };

    const script = generateZshCompletions(data);

    expect(script).toContain("--help");
    expect(script).toContain("-h");
    expect(script).toContain("Show help");
  });

  it("includes custom options with descriptions", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [
        { long: "verbose", short: "v", type: "boolean", description: "Verbose output" },
        { long: "output", short: "o", type: "string", description: "Output file" },
      ],
      subcommands: [],
    };

    const script = generateZshCompletions(data);

    expect(script).toContain("--verbose");
    expect(script).toContain("-v");
    expect(script).toContain("Verbose output");
    expect(script).toContain("--output");
    expect(script).toContain("-o");
    expect(script).toContain("Output file");
  });

  it("includes value spec for non-boolean options", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [
        { long: "count", type: "number", description: "Count" },
        { long: "file", type: "string", description: "File path" },
      ],
      subcommands: [],
    };

    const script = generateZshCompletions(data);

    expect(script).toContain(":value:");
  });

  it("includes subcommands in completion", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [],
      subcommands: [
        { name: "init", description: "Initialize project", options: [], subcommands: [] },
        { name: "build", description: "Build project", options: [], subcommands: [] },
      ],
    };

    const script = generateZshCompletions(data);

    expect(script).toContain("'init:Initialize project'");
    expect(script).toContain("'build:Build project'");
    expect(script).toContain("_describe 'command' commands");
  });

  it("generates separate functions for subcommands", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [],
      subcommands: [
        {
          name: "config",
          description: "Config commands",
          options: [{ long: "global", type: "boolean", description: "Global config" }],
          subcommands: [],
        },
      ],
    };

    const script = generateZshCompletions(data);

    expect(script).toContain("_my_cli_config()");
    expect(script).toContain("--global");
  });

  it("handles nested subcommands with routing", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [],
      subcommands: [
        {
          name: "config",
          description: "Config commands",
          options: [],
          subcommands: [
            { name: "get", description: "Get config", options: [], subcommands: [] },
            { name: "set", description: "Set config", options: [], subcommands: [] },
          ],
        },
      ],
    };

    const script = generateZshCompletions(data);

    expect(script).toContain("_my_cli_config()");
    expect(script).toContain("'get:Get config'");
    expect(script).toContain("'set:Set config'");
    expect(script).toContain("config)");
    expect(script).toContain("_my_cli_config");
  });

  it("excludes hidden commands from completions", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [],
      subcommands: [
        { name: "visible", description: "Visible command", options: [], subcommands: [] },
        {
          name: "hidden",
          description: "Hidden command",
          hidden: true,
          options: [],
          subcommands: [],
        },
      ],
    };

    const script = generateZshCompletions(data);

    expect(script).toContain("visible");
    expect(script).not.toContain("'hidden:Hidden command'");
  });

  it("escapes special characters in descriptions", () => {
    const data: CommandData = {
      name: "my-cli",
      options: [{ long: "test", type: "boolean", description: "Test [option] with brackets" }],
      subcommands: [],
    };

    const script = generateZshCompletions(data);

    expect(script).toContain("\\[option\\]");
  });
});
